### ISSUE TITLE
dnnFormPopup override is causing alignment issues in dnn9.1

### ISSUE THREAD

**Issue by wtatters** [2sic/dnn-skin-bootstrap3-instant#14]
file:  _dnn-overrides.scss	

Needed to remove the line for the popup to behave correctly in dnn9.1

/*
.dnnFormPopup { top: 50px!important; }
*/

**Comment by BeniFreitag** [comment]
When working with the HTML-module in DNN 9.1 the edit-dialog isn't shown properly. The solution suggested by wtatters works!
![dnn 91 bootstrap edit html](https://cloud.githubusercontent.com/assets/6669093/26442975/ec7a952a-4136-11e7-8f60-46cf1deb39da.png)

**Comment by raphael-m** [comment]
Note that this change might cause side-effects in older DNN versions (7.4 or 8). The line was added because of a bug that caused the modal window to be placed in a position outside of the viewport.

**Comment by lucatescari** [comment]
@raphael-m I tested it on DNN 7.4.2, DNN 8.0.4 and DNN 9.0.2 and it seems to be just fine. Do you know the exact version where this side-effect would appea?
