### ISSUE TITLE
Menu broken on pages with 2sxc modules (News, Blog, Content)

### ISSUE THREAD

**Issue by MIBICT** [2sic/dnn-skin-bootstrap3-instant#18]
I just installed this skin on testing site. 

Everything looks fine on pages without 2sxc App modules ([link](https://www.lokalno.eu/)) but on pages where 2sxc modules are installed - menu is broken (see [link1](https://www.lokalno.eu/Novosti) [link2](https://www.lokalno.eu/Blog) [link3](https://www.lokalno.eu/Maps)).

DNN version is 9.8.0 , skin is 3.01.00
Any idea of what can cause such behavior?

**Comment by MIBICT** [comment]
Update: 

Solved for 2sxc Content issue ([link3](https://www.lokalno.eu/Maps)) by adding koi.json in skin folder, but problem remains for News ([link1](https://www.lokalno.eu/Novosti)) and Blog ([link2](https://www.lokalno.eu/Blog)) App.

**Comment by iJungleboy** [comment]
Not sure - but I would really recommend you install the Bootstrap 4 theme instead of 3.

**Comment by MIBICT** [comment]
Thank You, Daniel, for quick response. I supposed that some class name is the same for skin and modules.
However - short after this post I've searched for "2sxc skin" and found that new one with Bootstrap 4. Working fine!
I have to say how much I appreciate 2sic / 2sxc contribution to community. It's priceless for non-profit projects like this one. Thank you very much!

**Comment by iJungleboy** [comment]
You're welcome :)
